### ISSUE TITLE
Missing 'LOCK TABLES' privilege to database user

### ISSUE THREAD

**Issue by aqan213** [cloudfoundry/pxc-release#11]
# Feature Request Info
## Problem you are trying to solve
I'm trying to use the pxc-release in app-autoscaler-release, I added a database 'autoscaler' and username is 'autoscaler', 
```
seeded_databases:
    - name: autoscaler
      password: ((database_password))
      username: autoscaler
```
but the user has no 'LOCK TABLES' privilege and it failed to deploy the app-autoscaler release.
Is it possible to add the 'LOCK TABLES' privilege to the database users or is there a user having 
the 'LOCK TABLES' privilege?
